
-- Insert sample products (Seller ID 1 is Ramy)
INSERT INTO products (title, description, price, category, `condition`, brand, model, quantity, status, shipping, local_pickup, seller_id) VALUES
('iPhone 14 Pro Max 256GB - Deep Purple', 'Latest iPhone model with ProMotion display and A16 Bionic chip.', 1099.99, 'smartphones', 'New', 'Apple', 'iPhone 14 Pro Max', 10, 'active', TRUE, FALSE, 1),
('Samsung Galaxy S23 Ultra 512GB - Phantom Black', 'Flagship Android phone with advanced camera system and S Pen.', 1199.00, 'smartphones', 'New', 'Samsung', 'Galaxy S23 Ultra', 8, 'active', TRUE, TRUE, 1),
('MacBook Pro 16-inch M2 Max - Space Gray', 'Powerful laptop for professionals with stunning Liquid Retina XDR display.', 2499.50, 'laptops', 'New', 'Apple', 'MacBook Pro 16 M2 Max', 5, 'active', TRUE, FALSE, 1),
('Dell XPS 15 Laptop - Intel Core i7, 32GB RAM, 1TB SSD', 'Premium Windows laptop with a beautiful InfinityEdge display.', 1899.00, 'laptops', 'Like New', 'Dell', 'XPS 15 9530', 3, 'active', TRUE, TRUE, 1),
('Sony WH-1000XM5 Noise Cancelling Headphones - Black', 'Industry-leading noise cancellation and superb sound quality.', 348.00, 'headphones', 'New', 'Sony', 'WH-1000XM5', 15, 'active', TRUE, FALSE, 1),
('Apple iPad Pro 12.9-inch M2 - 256GB Wi-Fi - Silver', 'The ultimate iPad experience with M2 chip performance.', 1099.00, 'tablets', 'New', 'Apple', 'iPad Pro 12.9 M2', 7, 'active', TRUE, FALSE, 1),
('Canon EOS R6 Mark II Mirrorless Camera Body', 'Full-frame mirrorless camera with advanced autofocus and video capabilities.', 2299.00, 'cameras', 'New', 'Canon', 'EOS R6 Mark II', 4, 'active', TRUE, FALSE, 1),
('Logitech MX Master 3S Wireless Mouse - Graphite', 'Advanced wireless mouse for productivity and comfort.', 99.99, 'accessories', 'New', 'Logitech', 'MX Master 3S', 25, 'active', TRUE, FALSE, 1),
('Samsung Odyssey G9 Gaming Monitor - 49-inch Curved QLED', 'Immersive gaming monitor with 240Hz refresh rate.', 1399.99, 'accessories', 'Like New', 'Samsung', 'Odyssey G9', 2, 'active', FALSE, TRUE, 1),
('Google Pixel 7 Pro 128GB - Obsidian', 'Google’s flagship phone with an amazing camera and clean Android experience.', 799.00, 'smartphones', 'Excellent', 'Google', 'Pixel 7 Pro', 6, 'active', TRUE, TRUE, 1),
('Lenovo Yoga 9i 14" 2-in-1 Laptop - Intel Evo Platform', 'Versatile 2-in-1 laptop with a stunning OLED display and rotating soundbar.', 1450.00, 'laptops', 'New', 'Lenovo', 'Yoga 9i 14', 5, 'active', TRUE, FALSE, 1),
('Bose QuietComfort Earbuds II - Triple Black', 'True wireless earbuds with world-class noise cancellation.', 279.00, 'headphones', 'New', 'Bose', 'QuietComfort Earbuds II', 12, 'active', TRUE, FALSE, 1),
('Samsung Galaxy Tab S8+ 128GB - Graphite', 'Powerful Android tablet with a large Super AMOLED display.', 749.99, 'tablets', 'Excellent', 'Samsung', 'Galaxy Tab S8+', 9, 'active', TRUE, TRUE, 1),
('Nikon Z7 II Mirrorless Camera with 24-70mm f/4 Lens', 'High-resolution full-frame camera for serious photographers.', 3399.95, 'cameras', 'New', 'Nikon', 'Z7 II Kit', 3, 'active', TRUE, FALSE, 1),
('Anker 737 Power Bank (PowerCore 24K)', 'High-capacity power bank with 140W output.', 149.99, 'accessories', 'New', 'Anker', '737 PowerCore 24K', 20, 'active', TRUE, FALSE, 1),
('Apple Watch Series 8 GPS 45mm - Midnight Aluminum', 'Advanced health and fitness tracking smartwatch.', 399.00, 'accessories', 'New', 'Apple', 'Watch Series 8', 18, 'active', TRUE, FALSE, 1),
('Sony Alpha 7 IV Full-Frame Mirrorless Camera Body', 'Hybrid camera excelling in both stills and video.', 2398.00, 'cameras', 'Like New', 'Sony', 'Alpha 7 IV', 3, 'active', TRUE, FALSE, 1),
('Microsoft Surface Laptop 5 13.5" - Intel Core i5, 16GB RAM', 'Sleek and lightweight Windows laptop for everyday use.', 1199.00, 'laptops', 'New', 'Microsoft', 'Surface Laptop 5', 6, 'active', TRUE, TRUE, 1),
('Sennheiser Momentum 4 Wireless Headphones - Black', 'Premium over-ear headphones with adaptive noise cancellation.', 329.95, 'headphones', 'Excellent', 'Sennheiser', 'Momentum 4', 8, 'active', TRUE, FALSE, 1),
('Amazon Kindle Paperwhite Signature Edition (32 GB)', 'Premium e-reader with wireless charging and auto-adjusting light.', 189.99, 'tablets', 'New', 'Amazon', 'Kindle Paperwhite SE', 15, 'active', TRUE, FALSE, 1),
('GoPro HERO11 Black Action Camera', 'Waterproof action camera with 5.3K video and HyperSmooth 5.0.', 399.99, 'cameras', 'New', 'GoPro', 'HERO11 Black', 10, 'active', TRUE, FALSE, 1),
('WD Black SN850X 2TB NVMe SSD with Heatsink', 'High-performance internal SSD for gaming and demanding applications.', 179.99, 'accessories', 'New', 'Western Digital', 'SN850X 2TB', 12, 'active', TRUE, FALSE, 1),
('OnePlus 11 5G 128GB - Titan Black', 'Flagship performance with Hasselblad camera system.', 699.00, 'smartphones', 'New', 'OnePlus', '11 5G', 7, 'active', TRUE, TRUE, 1),
('HP Spectre x360 14 2-in-1 Laptop - Nightfall Black', 'Premium convertible laptop with gem-cut design and OLED display.', 1549.99, 'laptops', 'Like New', 'HP', 'Spectre x360 14', 4, 'active', TRUE, FALSE, 1),
('JBL Charge 5 Portable Bluetooth Speaker - Black', 'Waterproof portable speaker with powerful sound and long battery life.', 179.95, 'accessories', 'New', 'JBL', 'Charge 5', 20, 'active', TRUE, FALSE, 1),
('Apple AirPods Pro (2nd generation)', 'Enhanced noise cancellation and personalized Spatial Audio.', 239.00, 'headphones', 'New', 'Apple', 'AirPods Pro 2', 30, 'active', TRUE, FALSE, 1),
('Microsoft Surface Pro 9 - Intel Core i5, 16GB RAM, 256GB SSD', 'Versatile 2-in-1 tablet and laptop.', 1299.00, 'tablets', 'Excellent', 'Microsoft', 'Surface Pro 9', 5, 'active', TRUE, TRUE, 1),
('Fujifilm X-T5 Mirrorless Camera Body - Silver', 'Retro-styled APS-C camera with high-resolution sensor.', 1699.00, 'cameras', 'New', 'Fujifilm', 'X-T5', 4, 'active', TRUE, FALSE, 1),
('Razer DeathAdder V3 Pro Wireless Gaming Mouse - Black', 'Ultralightweight ergonomic wireless gaming mouse.', 149.99, 'accessories', 'New', 'Razer', 'DeathAdder V3 Pro', 10, 'active', TRUE, FALSE, 1),
('Samsung Galaxy Watch 5 Pro 45mm LTE - Black Titanium', 'Durable smartwatch with advanced GPS and health tracking.', 429.00, 'accessories', 'Like New', 'Samsung', 'Galaxy Watch 5 Pro', 8, 'active', TRUE, FALSE, 1),
('Xiaomi 13 Pro 256GB - Ceramic White', 'High-end smartphone with Leica co-engineered cameras.', 950.00, 'smartphones', 'New', 'Xiaomi', '13 Pro', 6, 'active', TRUE, TRUE, 1),
('ASUS ROG Zephyrus G14 Gaming Laptop - Ryzen 9, RTX 4070', 'Compact and powerful gaming laptop with AniMe Matrix display.', 1799.99, 'laptops', 'New', 'ASUS', 'ROG Zephyrus G14', 3, 'active', TRUE, FALSE, 1),
('Sony LinkBuds S Truly Wireless Noise-Canceling Earbuds - Black', 'Small and light Hi-Res Audio wireless earbuds.', 148.00, 'headphones', 'Excellent', 'Sony', 'LinkBuds S', 15, 'active', TRUE, FALSE, 1),
('Lenovo Tab P11 Pro Gen 2 - 128GB', 'OLED Android tablet for entertainment and productivity.', 399.99, 'tablets', 'New', 'Lenovo', 'Tab P11 Pro Gen 2', 7, 'active', TRUE, TRUE, 1),
('Panasonic Lumix GH6 Mirrorless Camera Body', 'Micro Four Thirds camera focused on professional video production.', 1997.99, 'cameras', 'New', 'Panasonic', 'Lumix GH6', 2, 'active', TRUE, FALSE, 1),
('Elgato Stream Deck MK.2 - White', '15-key customizable LCD controller for streaming and content creation.', 149.99, 'accessories', 'New', 'Elgato', 'Stream Deck MK.2', 10, 'active', TRUE, FALSE, 1),
('Garmin Fenix 7X Sapphire Solar Multisport GPS Watch - Black DLC Titanium', 'Premium multisport watch with solar charging and advanced mapping.', 899.99, 'accessories', 'New', 'Garmin', 'Fenix 7X Sapphire Solar', 5, 'active', TRUE, FALSE, 1),
('DJI Mini 3 Pro Drone with RC Controller', 'Lightweight and powerful drone with tri-directional obstacle sensing.', 909.00, 'cameras', 'New', 'DJI', 'Mini 3 Pro', 6, 'active', TRUE, FALSE, 1),
('Alienware m18 Gaming Laptop - Intel Core i9, RTX 4080', 'High-performance gaming laptop with a large 18-inch display.', 2799.00, 'laptops', 'New', 'Alienware', 'm18', 2, 'active', TRUE, FALSE, 1),
('Beats Fit Pro True Wireless Noise Cancelling Earbuds - Black', 'Secure-fit wingtips, perfect for workouts.', 199.95, 'headphones', 'New', 'Beats', 'Fit Pro', 12, 'active', TRUE, FALSE, 1),
